TASK: "Cas_Stage2_Aug_Wing-S1_Wing"

CASCADE: 
  STAGE: 2
  STAGE1_MODEL_NAME: "resnet18"
  STAGE1_MODEL_PATH: "checkpoints/Cas_Stage1_Aug_Wing/2023-04-11_02-43-53_epoch_9_NME_2.21141.pth.tar"

DATA:
  TRAIN_PATH: "data/training_images_full_train.npz"
  TRAIN_PATH2: None
  TEST_PATH: "data/training_images_full_test.npz"
  TRAIN_AUGMENT: True

TRAIN: 
  LEARNING_RATE: 0.3
  BATCH_SIZE: 16
  NUM_EPOCHS: 100
  SAVE_MODEL: True
  LOSS: "Wing"

MODEL: 
  MODEL_NAME: "resnet50"
  NUM_OUTPUTS: 88
  PRETRAINED: True
  LOAD_MODEL: False
  LOAD_PATH: None