TASK: "raw_CNN_noAug_MSE_lr0.5_B4-2"

CASCADE: 
  STAGE: None
  STAGE1_MODEL_NAME: None
  STAGE1_MODEL_PATH: None

DATA:
  DATA_PATH: None
  TRAIN_PATH: "data/training_images_full_train.npz"
  TRAIN_PATH2: None
  TEST_PATH: "data/training_images_full_test.npz"
  TRAIN_AUGMENT: False

TRAIN: 
  LEARNING_RATE: 0.5
  BATCH_SIZE: 4
  NUM_EPOCHS: 100
  SAVE_MODEL: True
  LOSS: "MSE"

MODEL: 
  MODEL_NAME: "resnet18"
  NUM_OUTPUTS: 88
  PRETRAINED: True
  LOAD_MODEL: False
  LOAD_PATH: None